# Generated by Django 4.2.1 on 2023-06-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_alter_post_author_alter_post_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
    ]
